################################
# Run Linter against code base #
################################

name: main_workflow
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_codigo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install

    - name: Lint files
      run: |
        npm run lint


  Cypress_job:
    runs-on: ubuntu-latest
    needs: Linter_job
    steps:
    - name: checkout_codigo
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        config-file: cypress.json
      # let's give this action an ID so we can refer
      # to its output values later
      id: cypress
      # Continue the build in case of an error, as we need to set the
      # commit status in the next step, both in case of success and failure
      continue-on-error: true
    - name: "Result artifact"
      run: |
        echo ${{ steps.cypress.outcome }}  > result.txt
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v2
      with:
        name: result.txt
        path: result.txt



  Add_badge_job:
    runs-on: ubuntu-latest
    if: ${{always()}}
    needs: Cypress_job
    steps:
    - name: checkout_codigo
      uses: actions/checkout@v2
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: result.txt
    - name: output-artifact
      run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
    - name: Action Update Readme
      uses: ./.github/actions/badge/
      # id: hello 
      with:
        resultado_test: ${{ steps.cypress.outputs.cypress_outcome }}
        # https://www.danielleheberling.xyz/blog/github-actions/
    - name: Push cambios Readme
      run: |
        git config user.name KevinCamos
        git config user.email kevincamossoto@gmail.com
        git add .
        git commit -m "update readme"
        git push 


  Deploy_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
    - name: checkout_codigo
      uses: actions/checkout@v2
    - name: vercel-action
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
        # vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
        working-directory: ./
# https://vercel.com/kevincamos/workflowactionsdaw/HeBe4wxE8FG23zW64GZbcrDF3KhX
# https://workflowactionsdaw-9931pzwjv-kevincamos.vercel.app/



  Notification_job:
    runs-on: ubuntu-latest
    if: ${{always()}}
    needs: [Add_badge_job, Deploy_job]
    steps:
      - name: checkout_codigo
        uses: actions/checkout@v2
      - name: Action Update Readme
        uses: ./.github/actions/email/
        # id: hello 
        with:
          linter_job: ${{ needs.Linter_job.result }}
          cypress_job: ${{ needs.Cypress_job.result }}
          add_badge_job: ${{ needs.Add_badge_job.result }}
          deploy_job: ${{ needs.Deploy_job.result }}
          send_from: ${{ secrets.MY_EMAIL}}
          send_to: ${{ secrets.EMAIL_TO}}
          apy_key: ${{ secrets.KEY_MAILCHIMP}}
          